from werkzeug.security import generate_password_hash
from app.models import db, House

# Adds a demo user, you can add other users here if you want
def seed_houses():

    """
    Model:
    House(host_id=, name="", street_1="", city="", state="", postal_code="", house_pic_url="", description="", max_guests=, num_bedrooms=, num_beds=, num_baths=, price=, smoking=True, pets_allowed=True, wifi=False, longitude=, latitude=)
    """


    mary_mayo_hall = House(host_id=3, name='Mary Mayo Hall', street_1='361 Delta Ct, East Lansing, MI 48825', city='East Lansing', state='MI', postal_code=48825, house_pic_url='https://live.staticflickr.com/6019/6241359519_991ed9814a_b.jpg', description='Located on the MSU campus, originally named Sylvan Lodge, Mary Mayo Hall was located in a small park which can be seen in a group of trees east of the building. The hall offers a music living-learning option.', max_guests=300, num_bedrooms=50, num_beds=100, num_baths=30, price=150, smoking=False, pets_allowed=True, wifi=False, longitude=42.725, latitude=-84.48)
    ss_valley_camp = House(host_id=4, name='SS Valley Camp', street_1='326 E Portage Ave, Sault Ste. Marie, MI 49783', city='Sault Ste. Marie', state='MI', postal_code=49783, house_pic_url='https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/SS_Valley_Camp_bow.jpg/1200px-SS_Valley_Camp_bow.jpg', description='SS Valley Camp is a lake freighter that served on the Great Lakes for almost 50 years and is now a museum ship', max_guests=200, num_bedrooms=100, num_beds=100, num_baths=50, price=200, smoking=False, pets_allowed=True, wifi=False, longitude=46.499167, latitude=-84.336389)
    south_lyon_hotel = House(host_id=3, name='South Lyon Hotel', street_1='201 N Lafayette St, South Lyon, MI 48178', city='South Lyon', state='MI', postal_code=48178, house_pic_url='https://lh3.googleusercontent.com/CL0ijx4cpOIoTjJs4fUqdPqK7xknGbirULe49nNWd5kkG1wX_VzXya4Y_GhN9KO74z6zPg=s115', description='Relaxed 2-floor American eatery in an iconic 1860s hotel morphs into a live-music venue at night.', max_guests=100, num_bedrooms=60, num_beds=60, num_baths=20, price=170, smoking=False, pets_allowed=True, wifi=False, longitude=42.460556, latitude=-83.651667)
    michigan_state_capital = House(host_id=3, name='Michigan State Capitol', street_1='100 N Capitol Ave, Lansing, MI 48933', city='Lansing', state='MI', postal_code=48933, house_pic_url='https://res.cloudinary.com/miles-extranet-dev/image/upload/ar_16:9,c_fill,w_1000,g_face,q_50/Michigan/migration_photos/B4183/B4183-StateCapitol.jpg', description='The Michigan State Capitol is the building that houses the legislative branch of the government of the U.S. state of Michigan.', max_guests=60, num_bedrooms=30, num_beds=100, num_baths=10, price=100, smoking=False, pets_allowed=True, wifi=False, longitude=42.733601, latitude=-84.55547)
    dixboro_general_store = House(host_id=4, name='Dixboro General Store', street_1='5206 Plymouth Rd, Ann Arbor, MI 48105', city='Ann Arbor', state='MI', postal_code=48105, house_pic_url='https://i.pinimg.com/originals/81/c7/14/81c714aa3c8c0004ddb00727a5a67d25.jpg', description='Don’t let our name fool you.  This historic store, and the adjoining Merchants Home, houses one of the busiest gift and furnishing stores in Michigan.', max_guests=50, num_bedrooms=25, num_beds=25, num_baths=20, price=80, smoking=True, pets_allowed=True, wifi=False, longitude=42.312222, latitude=-83.656111)
    uss_edson = House(host_id=3, name='USS Edson', street_1='680 Martin Street Bay City, MI 48706', city='Bay City', state='MI', postal_code=48706, house_pic_url='https://media.mlive.com/news/baycity_impact/photo/ussedson1aajpg-0412821c7b7edd37.jpg', description='The museum will be permanently housed in the USS Edson, a retired United States Navy destroyer that has recently been converted to a museum.', max_guests=200, num_bedrooms=100, num_beds=100, num_baths=60, price=200, smoking=False, pets_allowed=False, wifi=False, longitude=43.613889, latitude=-83.868889)
    lamar_hotel = House(host_id=4, name='LaMar Hotel', street_1='1581 S Washington AveSaginaw, MI 48601', city='AveSaginaw', state='MI', postal_code=48601, house_pic_url='https://atlas-assets.roadtrippers.com/uploads/place_image/image/14598790/-strip_-quality_60_-interlace_Plane_-resize_640x360_U__-gravity_center_-extent_640x360/place_image-image-57981427-97d3-47c4-866d-15b5c98f3d32.jpg', description="This inn is said to be the home of an apparition that has been spotted standing at the far end of the corridor on the third floor, disappearing when approached. The innkeeper's quarters is also believed to have a ghostly presence, and may even be that of a former owner.", max_guests=20, num_bedrooms=10, num_beds=10, num_baths=10, price=100, smoking=False, pets_allowed=True, wifi=False, longitude=43.488611, latitude=-83.3975)
    white_river_light_house = House(host_id=3, name='White River Light House Station', street_1=' 6199 Murray Rd, Whitehall, MI 49461', city='Whitehall', state='MI', postal_code=49461, house_pic_url='https://www.lighthousefriends.com/WhiteRiver_1952_cg.jpg', description='The White River Light is a lighthouse on Lake Michigan near the city of Whitehall, Michigan. It sits on a thin peninsula of land separating Lake Michigan from White Lake. The building was built in 1875.', max_guests=20, num_bedrooms=10, num_beds=10, num_baths=10, price=50, smoking=False, pets_allowed=True, wifi=False, longitude=43.37473, latitude=-86.42433)
    forest_lawn_cemetary_and_mausoleum = House(host_id=4, name='Forest Lawn Cemetery & Mausoleum', street_1='Glen Arbor, MI 49636', city='Glen Arbor', state='MI', postal_code=49636, house_pic_url='https://forest-lawn.s3-us-west-1.amazonaws.com/wp-content/uploads/2018/03/GLENDALE.jpg', description='A site, by Forest Haven Road and M-22, where lies the old Glen Arbor Township Cemetery. It was used primarily in the 1800s and beginning of the 1900s for the early pioneers of the area', max_guests=100, num_bedrooms=80, num_beds=80, num_baths=50, price=100, smoking=False, pets_allowed=True, wifi=False, longitude=44.896111, latitude=-85.998333)
    whaley_historic_museum = House(host_id=3, name='Whaley Historic Museum', street_1='624 E Kearsley St, Flint, MI 48503', city='St, Flint', state='MI', postal_code=48503, house_pic_url='https://www.mlive.com/resizer/8Difgi3Moc26NoLnMukXMJFmV9k=/450x0/smart/arc-anglerfish-arc2-prod-advancelocal.s3.amazonaws.com/public/OZIYZA6AAFDUJKLG5HAZD4BKQU.JPG', description='Guided tours are offered of this 19th-century Victorian house with historical collections.', max_guests=60, num_bedrooms=10, num_beds=20, num_baths=10, price=300, smoking=False, pets_allowed=False, wifi=False, longitude=43.02, latitude=-83.684)
    road_house = House(host_id=4, name='The Road House', street_1='4112 Lansing Ave, Jackson, MI 49202', city='Jackson', state='MI', postal_code=49202, house_pic_url='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPrBa9e-nwMysAF4eLHqDVFCw8uglxAbLthQ&usqp=CAU', description='Our historical tavern is called the Roadhouse now, but in the early 1940s, the building at 4112 Lansing Ave. was the Meadow Lark Inn', max_guests=10, num_bedrooms=4, num_beds=4, num_baths=2, price=50, smoking=True, pets_allowed=True, wifi=False, longitude=42.733611, latitude=-84.546667)
    nunica_cemetary = House(host_id=3, name='Nunica Cemetery', street_1='12189 Cleveland St, Nunica, MI 49448', city='Nunica', state='MI', postal_code=49448, house_pic_url='https://lh3.googleusercontent.com/4JzbsYV4zMktAVyAyTEocWLBRiid--SKQwqB3AIyfoWw9Jjw3HhO6g0nkQtCHXUCidavBmg=s151', description="This Michigan graveyard has been called one of the most haunted cemeteries in Michigan...and it's one where a lot of ghost-hunters & paranormal investigators flock to. It's Nunica Cemetery, established in 1883", max_guests=30, num_bedrooms=10, num_beds=10, num_baths=10, price=80, smoking=True, pets_allowed=True, wifi=False, longitude=43.079722, latitude=-86.067222)
    perrys_schuch_hotel = House(host_id=3, name="Perry's Schuch Hotel", street_1='303 N Hamilton St, Saginaw, MI 48602', city='Saginaw', state='MI', postal_code=48602, house_pic_url='https://lh3.googleusercontent.com/LvKo67iwGnXEPjdxAQ5EWcnxZtk80J4kOL_oW6Sztlb3j93z9z1h9gdI74d6TByM68JKgQ=s119', description="For 138 years the historic Schuch Hotel, located at 301 N. Hamilton has stood as an icon of Saginaw's Old Town district", max_guests=200, num_bedrooms=100, num_beds=100, num_baths=50, price=200, smoking=False, pets_allowed=False, wifi=False, longitude=43.416944, latitude=-83.963611)
    masonic_temple_detroit = House(host_id=4, name='Masonic Temple Detroit', street_1='500 Temple St, Detroit, MI 48201', city='Detroit', state='MI', postal_code=48201, house_pic_url='https://lh3.googleusercontent.com/PxD96kzCgbkwR5fcuy328Lv5odnx2RvQPOtc3asaJpgm3zJKCv-8fjyz5sG6M7v2_1aaag=s128', description="The Detroit Masonic Temple is the world's largest Masonic Temple. Located in the Cass Corridor of Detroit, Michigan, at 500 Temple Street, the building serves as a home to various masonic organizations including the York Rite Sovereign College of North America", max_guests=150, num_bedrooms=200, num_beds=100, num_baths=50, price=200, smoking=False, pets_allowed=True, wifi=False, longitude=-42.34178977554219, latitude=-83.06015732703682)
    holmeden_hall = House(host_id=3, name='Holmdene Hall', street_1='Holmdene, Grand Rapids, MI 49506', city='Grand Rapids', state='MI', postal_code=49506, house_pic_url='https://michigansotherside.com/wp-content/uploads/2016/04/Haunted-Holmdene-Aquinas.jpg', description="There's a beautiful English Tudor Mansion sitting on Aquinas College's campus called Holmdene Hall that is rumored to be haunted. They say the historic building houses creatures that go bump in the night, elevators that move themselves, and lights that flicker.", max_guests=300, num_bedrooms=150, num_beds=150, num_baths=50, price=170, smoking=False, pets_allowed=False, wifi=False, longitude=42.961411583592074, latitude=-85.62723470201435)
    state_theatre = House(host_id=4, name='State Theatre', street_1='913 Washington Ave, Bay City, MI 48708', city='Bay City', state='MI', postal_code=48708, house_pic_url='https://statetheatrebaycity.com/assets/files/theatre-bijou.gif', description='Historic 1930s building with art deco design features live performance art including film & music, and of course, GHOST!', max_guests=50, num_bedrooms=20, num_beds=20, num_baths=5, price=220, smoking=False, pets_allowed=True, wifi=False, longitude=43.599794376794826, latitude=-83.8878385019938)
    marquette_harbor_lighthouse = House(host_id=3, name='Marquette Harbor Lighthouse', street_1='300 N Lakeshore Blvd, Marquette, MI 49855', city='Marquette', state='MI', postal_code=49855, house_pic_url='https://blog.gregdisch.com/wp-content/uploads/2018/03/Marquette-Harbor-Lighthouse-20170915-IMG_1263.jpg', description='The Marquette Harbor Light is located on Lake Superior in Marquette, Michigan, a part of the Upper Peninsula.', max_guests=20, num_bedrooms=10, num_beds=10, num_baths=5, price=150, smoking=False, pets_allowed=True, wifi=False, longitude=47.45038607627499, latitude=-87.24028414397175)

    big_bay = House(host_id=1, name="Big Bay Point Light", street_1="4674 Co Rd KCB", city="Big Bay", state="MI", postal_code="49808", house_pic_url="", description="The Big Bay Point Light is a lighthouse which stands on a tall bluff over a rocky point near Big Bay, Michigan.", max_guests=12, num_bedrooms=6, num_beds=6, num_baths=4, price=300, smoking=True, pets_allowed=True, wifi=False, longitude=46.840278, latitude=-87.681944)
    eloise_arms = House(host_id=1, name="Eloise Arms", street_1="3758 Henry Ruff Rd", city="Westland", state="MI", postal_code="48186", house_pic_url="", description="Take a comfortable stay where you will receive superb treatment and an escape from life!", max_guests=30, num_bedrooms=15, num_beds=30, num_baths=15, price=100, smoking=True, pets_allowed=True, wifi=False, longitude=42.28117, latitude=-83.33918)
    landmark_inn = House(host_id=1, name="Landmark Inn", street_1="230 N Front St", city="Marquette", state="MI", postal_code="49855", house_pic_url="", description="Come visit our historic hotel and have chat with our librarian on staff!", max_guests=40, num_bedrooms=30, num_beds=60, num_baths=30, price=150, smoking=False, pets_allowed=True, wifi=False, longitude=46.545, latitude=-87.392)
    whitney_mansion = House(host_id=1, name="The Whitney Mansion", street_1="4421 Woodward Ave", city="Detroit", state="MI", postal_code="48201", house_pic_url="https://www.michiganhauntedhouses.com/real-haunt-photo/david-whitney-house--whitney_863.jpg", description="Originally, constructed for lumber baron, David Whitney, this mansion's permanent residents Whitney and his life live here eternally.", max_guests=15, num_bedrooms=6, num_beds=12, num_baths=4, price=225, smoking=False, pets_allowed=True, wifi=False, longitude=42.352658, latitude=-83.062097)
    fort_holmes = House(host_id=1, name="Fort Holmes", street_1="2234 Fort Holmes Rd", city="Mackinac Island", state="MI", postal_code="49757", house_pic_url="https://www.ghostquest.net/uploads/7/9/0/2/79029746/ft-holmes-2-mackinac-island-michigan_1.jpg", description="Fort Holmes is a fortified earthen redoubt located on the highest point of Mackinac Island. Originally built in 1814 by British forces during the War of 1812, the redoubt was improved by that army throughout the course of the war (1812–1814) to help defend the adjacent Fort Mackinac from a possible attack by the U.S. Army.", max_guests=6, num_bedrooms=3, num_beds=2, num_baths=2, price=75, smoking=True, pets_allowed=True, wifi=False, longitude=45.858336, latitude=-84.616442)
    grand_hotel = House(host_id=1, name="Mackinac Island Grand Hotel", street_1="286 Grand Ave", city="Mackinac Island", state="MI", postal_code="49757", house_pic_url="https://ewscripps.brightspotcdn.com/dims4/default/5ee33dc/2147483647/strip/true/crop/640x360+0+33/resize/1280x720!/quality/90/?url=https%3A%2F%2Fmediaassets.wxyz.com%2Fphoto%2F2018%2F09%2F12%2FGrand%20Hotel%20Fall2017-9-1-e1509209080371_1536760330496.jpg_97228743_ver1.0_640_480.jpg", description="The Grand Hotel is a historic hotel and coastal resort on Mackinac Island, Michigan, a small island located at the eastern end of the Straits of Mackinac within Lake Huron between the state's Upper and Lower peninsulas. Constructed in the late 19th century, the facility advertises itself as having the world's largest porch.", max_guests=150, num_bedrooms=60, num_beds=120, num_baths=60, price=349, smoking=True, pets_allowed=False, wifi=False, longitude=45.851111, latitude=-84.625833)
    fort_wayne = House(host_id=1, name="Fort Wayne", street_1="6325 W Jefferson Ave", city="Detroit", state="MI", postal_code="", house_pic_url="", description="", max_guests=, num_bedrooms=, num_beds=, num_baths=, price=, smoking=True, pets_allowed=True, wifi=False, longitude=, latitude=)

    houses = [grand_hotel, fort_holmes, whitney_mansion, landmark_inn, eloise_arms, big_bay, mary_mayo_hall, ss_valley_camp, south_lyon_hotel, michigan_state_capital, dixboro_general_store, uss_edson, lamar_hotel,white_river_light_house, road_house, nunica_cemetary, perrys_schuch_hotel, masonic_temple_detroit, holmeden_hall, state_theatre, marquette_harbor_lighthouse ]

    for house in houses:
        db.session.add(house)

    db.session.commit()

# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and resets
# the auto incrementing primary key
def undo_users():
    db.session.execute('TRUNCATE houses;')
    db.session.commit()
