"""update users table

Revision ID: 16b1f0da93ad
Revises: ffdc0a98111c
Create Date: 2020-12-28 17:21:32.428347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b1f0da93ad'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('bio', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('profile_pic_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('is_host', sa.Boolean(), nullable=False))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'profile_pic_url')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'is_host')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
