"""create bookings table

Revision ID: 2ad1fc99343d
Revises: 70b8d0463a00
Create Date: 2020-12-29 10:36:10.565305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad1fc99343d'
down_revision = '70b8d0463a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('checkin', sa.DateTime(), nullable=False),
    sa.Column('checkout', sa.DateTime(), nullable=False),
    sa.Column('num_guests', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_constraint('houses_state_id_fkey', 'houses', type_='foreignkey')
    # op.drop_column('houses', 'state_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('houses', sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.create_foreign_key('houses_state_id_fkey', 'houses', 'states', ['state_id'], ['id'])
    op.drop_table('bookings')
    # ### end Alembic commands ###
