"""create amenities table

Revision ID: 6b607892b2a7
Revises: 058e196abad8
Create Date: 2020-12-29 10:47:15.161124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b607892b2a7'
down_revision = '058e196abad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amenity_name', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=25)),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amenities')
    # ### end Alembic commands ###
