"""create states table

Revision ID: 058e196abad8
Revises: c9976e355f3f
Create Date: 2020-12-29 10:18:20.566420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058e196abad8'
down_revision = 'c9976e355f3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('states')
    # ### end Alembic commands ###
