"""empty message

Revision ID: aa6f0dc506bd
Revises: 178ae2418526
Create Date: 2021-02-03 10:03:20.443801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6f0dc506bd'
down_revision = '178ae2418526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amenities', sa.Column('icon', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amenities', 'icon')
    # ### end Alembic commands ###
